### ISSUE TITLE
Add a namespace check for loot table injection

### ISSUE THREAD

**Issue by liach** [polgaria/ExtraDiscs#1]
https://github.com/polgaria/ExtraDiscs/blob/f59b8d120c6e340cec491f460983ef9ec8e0f127/src/main/java/site/geni/ExtraDiscs/ExtraDiscs.java#L59

Apparently railcraft mod injects to vanilla dungeon loot table from a loot table with the exact same path but a different namespace (railcraft instead), causing a conflict. See Railcraft/Railcraft#1833

Moreover, it is suggested to add a loot pool to the loot table instead of simply inserting entries into the pool.

**Comment by geniiii** [comment]
ah, sorry! i rushed the whole loot table thing a lot, will fix

**Comment by Dimentive** [comment]
Thanks for the quick fix! 💙
